services:
  - type: web
    name: telegram-sticker-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
